name: Copy Files using WinRM

on:
  push:
    branches:
      - main  # Adjust to your branch

jobs:
  copy-files:
    runs-on: self-hosted  # Ensure this is a Linux self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy PowerShell Script to Windows Server using WinRM
        run: |
          # Define Windows Server details
          server="${{ secrets.WINDOWS_HOST }}"
          username="${{ secrets.WINDOWS_USER }}"
          password="${{ secrets.WINDOWS_PASSWORD }}"
          local_script_path="/home/github/write_hello.ps1"
          remote_script_path="C:\\deploy\\write_hello.ps1"

          # Start the WinRM session and upload the PowerShell script
          python3 -c "
import winrm

# Read the PowerShell script as text
with open('${local_script_path}', 'r') as file:
    script_content = file.read()

# Start WinRM session
session = winrm.Session(f'http://{server}:5985/wsman', auth=('${username}', '${password}'), transport='ntlm')

# Step 1: Send the PowerShell script to the Windows server (no base64)
powershell_create_script = f'''
Set-Content -Path \"{remote_script_path}\" -Value \"{script_content.replace('\"', '\"\"')}\"
'''

# Run the PowerShell command to create the script on Windows
create_result = session.run_ps(powershell_create_script)
print('File creation output:')
print(create_result.std_out.decode())
print(create_result.std_err.decode())

# Step 2: Run the PowerShell script on Windows
powershell_run_script = f'powershell.exe -ExecutionPolicy Bypass -File \"{remote_script_path}\"'
run_result = session.run_cmd(powershell_run_script)

print('Script execution output:')
print(run_result.std_out.decode())
print(run_result.std_err.decode())
          "
