
name: Copy Files using WinRM

on:
  push:
    branches:
      - main  # Adjust to your branch

jobs:
  copy-files:
    runs-on: self-hosted  # Ensure this is a Linux self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Files to Windows Server using WinRM
        run: |
          python3 <<EOF
          import winrm
          # Define Windows Server details
          server = "${{ secrets.WINDOWS_HOST }}"
          username = "${{ secrets.WINDOWS_USER }}"
          password = "${{ secrets.WINDOWS_PASSWORD }}"
          # Establish WinRM Session
          session = winrm.Session(f'http://{server}:5985/wsman', auth=(username, password), transport="ntlm")
          # PowerShell Command to Copy Files from Linux to Windows
          copy_command = "Copy-Item -Path '\\\\172.16.3.79\\home\\github\\build.txt\\*' -Destination 'C:\\deploy' -Recurse -Force"
          result = session.run_ps(copy_command)
          print(result.std_out.decode())
          EOF
