name: Copy Files using WinRM

on:
  push:
    branches:
      - main  # Adjust to your branch

jobs:
  copy-files:
    runs-on: self-hosted  # Ensure this is a Linux self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip3 install pywinrm

      - name: Run Python script to copy and execute PowerShell file
        run: |
          python3 /home/github/write_hello.py
